# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "terminal-table", "~> 3.0"

gem "tty-prompt", "~> 0.23.1"

gem "rspec", "~> 3.10"

gem "whirly", "~> 0.3.0"

gem "paint", "~> 2.2"

gem "uri", "~> 0.11.0"

gem "openssl", "~> 2.2"
